name: Python application

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort
    - name: Format code with black
      run: |
        black --check --exclude=worker/requests .
    - name: Order imports with isort
      run: |
        isort --check --profile black --skip worker/requests .
